name: "CI/CD"

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: make test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/report.xml
